### ISSUE TITLE
Drop or transfer this repo?

### ISSUE THREAD

**Issue by MoOx** [kud/fix-all-the-things#18]
@kud I think you are the only one using it and it seems that you didn't use it for a year.
Are you open to drop it ?
If you want you can transfert it to yourself (I cannot transfer you the repo per github restrictions).

**Comment by kud** [comment]
Okay. :)

**Comment by kud** [comment]
Apparently you cannot transfer to a person, only orga.

**Comment by MoOx** [comment]
Yes you can, you just need to have the admin right. Transfered to me, then to you

**Comment by kud** [comment]
Thank you @MoOx  ;)
