### ISSUE TITLE
[CleanShotX] Emoji can't be added in text

### ISSUE THREAD

**Issue by kud** [kud/fix-all-the-things#26]
**Describe the bug**

In edit mode on a screenshot, text section doesn't accept any emoji

**To Reproduce**

- Make a screenshot
- Open the edit mode
- Add a text section
- Add an emoji
- The emoji is removed after editing

**Device**

 - OS: `OS X 10.15.4`
 - App Version: `3.1.2`

**Comment by ghost** [comment]
It's fixed 
![image](https://user-images.githubusercontent.com/88319985/136978989-1043aec0-b07d-4bdf-a745-ce0851232886.png)

**Comment by kud** [comment]
That's right! Thanks :)
