### ISSUE TITLE
[IE] doesn't accept spaces on transform: translate

### ISSUE THREAD

**Issue by kud** [kud/fix-all-the-things#8]
http://codepen.io/anon/pen/nEzCJ

When you've got spaces after brackets, IE takes `-webkit-transform` property, not `transform`.
And as IE doesn't understand `-webkit-transform`...

Tested on IE11, Windows Vista.

![screen shot 2014-07-21 at 15 10 06](https://cloud.githubusercontent.com/assets/655838/3643754/68add572-10d8-11e4-9969-e6ab628fd845.png)

**Comment by zhoock** [comment]
Так я не понял, есть решение проблемы или нет?

**Comment by kud** [comment]
Not sure to understand.

**Comment by zhoock** [comment]
anyway remains a problem with the alignment in ie
http://codepen.io/zhoock/pen/zxXWvO?editors=110
a scroll bar appears
